package core

type LvResultT lv_result_t
type LvObjT lv_obj_t
type LvDrawBufT lv_draw_buf_t
type LvColorFormatT lv_color_format_t
type LvColorT lv_color_t
type LvColor16T lv_color16_t
type LvColor32T lv_color32_t
type LvColorHsvT lv_color_hsv_t
type LvColor16aT lv_color16a_t
type LvOpaT lv_opa_t
type LvRadiusT lv_radius_t
type LvStyleT lv_style_t
type LvStyleTransitionDscT lv_style_transition_dsc_t
type LvAnimT lv_anim_t
type LvImageDscT lv_image_dsc_t
type LvAreaT lv_area_t
type LvPointT lv_point_t
type LvLayerT lv_layer_t
type LvChartSeriesT lv_chart_series_t
type LvChartCursorT lv_chart_cursor_t
type LvDirT lv_dir_t
type LvAnimEnableT lv_anim_enable_t
type LvBlendModeT lv_blend_mode_t
type LvEventT lv_event_t
type LvEventCodeT lv_event_code_t
type LvEventCbT lv_event_cb_t
type LvEventDscT lv_event_dsc_t

type LvIndevT lv_indev_t
type LvPointPreciseT lv_point_precise_t
type LvDisplayT lv_display_t
type LvThemeT lv_theme_t
type LvTimerT lv_timer_t
type LvAlignT lv_align_t
type ValuePreciseT lv_value_precise_t
type LvStyleSelectorT lv_style_selector_t
type LvStylePropT lv_style_prop_t
type LvPartT lv_part_t
type LvStyleValueT lv_style_value_t
type LvStyleResT lv_style_res_t
type LvStyleStateCmpT lv_style_state_cmp_t
